name: bio
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - biopython
  - h5py
  - hdf5
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch
  - pyyaml
  - scikit-learn
  - scipy
  - seaborn
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - opt-einsum
    - pickleshare
    - pyaml
    - sparsemax
    - tensorboard>=2.20
    - transformers
    - sentencepiece
