balanced_loss: no
batch_size: 256
checkpoint:
config: /Users/shimpitech/vincent/protein-localization/sweeps/layer_seeds3_dc48_stacked/configs/loc_layer24_mean_dc48_seed921.yaml
embedding_mode: lm
eval_on_test: yes
experiment_name: layer24_mean_dc48_loc_seed921
key_format: hash
log_iterations: 100
loss_function: LocCrossEntropy
max_length: 6000
min_train_acc: 0
model_parameters:
  dropout: 0.25
  hidden_dim: 32
  n_hidden_layers: 0
  output_dim: 10
  pooling: mean
  proj_dim: 48
model_type: PoolingFFN
n_draws: 200
num_epochs: 5000
optimizer: Adam
optimizer_parameters:
  lr: 0.0001
patience: 80
seed: 921
solubility_loss: 0
target: loc
test_embeddings: /Users/shimpitech/vincent/protein-localization/data_files/deeploc_test_set_layer24.h5
test_remapping: /Users/shimpitech/vincent/protein-localization/data_files/deeploc_test_set_remapped.fasta
train_embeddings: /Users/shimpitech/vincent/protein-localization/data_files/deeploc_our_train_set_layer24.h5
train_remapping: /Users/shimpitech/vincent/protein-localization/data_files/deeploc_our_train_set_remapped.fasta
unknown_solubility: yes
val_embeddings: /Users/shimpitech/vincent/protein-localization/data_files/deeploc_our_val_set_layer24.h5
val_remapping: /Users/shimpitech/vincent/protein-localization/data_files/deeploc_our_val_set_remapped.fasta
