#!/usr/bin/env python3
"""
Layer sweep — repeat the head-to-head pooling comparison across ProtX layers.

From the project spec (Section 5.1):
  "Layer sweep: repeat the head-to-head on a handful of layers
   (last, last-4, middle, early) — does covariance pooling's advantage hold
   across layers?"

For every (layer, method) pair the script:
  1. Builds a temporary config with the embedding paths overridden to the
     per-layer H5 files generated by embed_layers_h5.py.
  2. Runs train_meltome.py / train.py as a subprocess.
  3. After all runs finish, prints a (layer × method) results table.

Default layers map to quartiles of ProtX depth (24 encoder blocks):
    6  → early    (~25 %)
   12  → middle   (~50 %)
   18  → late     (~75 %)
   24  → last     (100 %)

Prerequisites — generate the per-layer H5 files first (GPU-intensive, one-time):
    python scripts/embed_layers_h5.py \\
        --fasta <train.fasta> <val.fasta> <test.fasta> \\
        --layers 6 12 18 24

Usage (Meltome):
    python scripts/run_layer_sweep.py \\
        --train-fasta data_files/flip_meltome/prepared/human_cell/human_cell_train.fasta \\
        --val-fasta   data_files/flip_meltome/prepared/human_cell/human_cell_val.fasta \\
        --test-fasta  data_files/flip_meltome/prepared/human_cell/human_cell_test.fasta \\
        --task meltome --methods mean cov hybrid --layers 6 12 18 24

Usage (DeepLoc):
    python scripts/run_layer_sweep.py \\
        --train-fasta data_files/deeploc_our_train_set.fasta \\
        --val-fasta   data_files/deeploc_our_val_set.fasta \\
        --test-fasta  data_files/deeploc_test_set.fasta \\
        --task loc --methods mean cov hybrid
"""

from __future__ import annotations

import argparse
import csv
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path

import yaml


PROJECT_ROOT = Path(__file__).resolve().parent.parent

TRAIN_SCRIPTS = {
    'loc':     'train_subcellular_localization.py',
    'meltome': 'train_meltome.py',
}

# Base configs used to inherit all hyperparameters (lr, batch, patience, …).
# Embedding paths are overridden per (layer, method) run.
BASE_CONFIGS = {
    'loc': {
        'mean':   PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'mean.yaml',
        'cov':    PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'cov.yaml',
        'hybrid': PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'hybrid.yaml',
        'la':     PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'la.yaml',
        'la_cov': PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'la_cov.yaml',
    },
    'meltome': {
        'mean':   PROJECT_ROOT / 'configs' / 'meltome' / 'mean.yaml',
        'cov':    PROJECT_ROOT / 'configs' / 'meltome' / 'cov.yaml',
        'hybrid': PROJECT_ROOT / 'configs' / 'meltome' / 'hybrid.yaml',
        'la':     PROJECT_ROOT / 'configs' / 'meltome' / 'la.yaml',
        'la_cov': PROJECT_ROOT / 'configs' / 'meltome' / 'la_cov.yaml',
    },
}

DEFAULT_LAYERS  = [6, 12, 18, 24]
DEFAULT_METHODS = ['mean', 'cov', 'hybrid', 'la', 'la_cov']


# ──────────────────────────────────────────────────────────────────────────────
# Path helpers  (mirror the naming from embed_layers_h5.py)
# ──────────────────────────────────────────────────────────────────────────────

def layer_h5(fasta: Path, layer: int) -> Path:
    return fasta.with_name(f"{fasta.stem}_layer{layer:02d}.h5")


def remapped(fasta: Path) -> Path:
    return fasta.with_name(f"{fasta.stem}_remapped.fasta")


# ──────────────────────────────────────────────────────────────────────────────
# Validation
# ──────────────────────────────────────────────────────────────────────────────

def validate_inputs(
    train_fasta: Path, val_fasta: Path, test_fasta: Path, layers: list[int],
) -> list[int]:
    """Return the subset of layers for which all three H5 files already exist."""
    ready, absent = [], []
    for layer in layers:
        files = [layer_h5(f, layer) for f in (train_fasta, val_fasta, test_fasta)]
        if all(f.exists() for f in files):
            ready.append(layer)
        else:
            absent.append(layer)
            for f in files:
                if not f.exists():
                    print(f'  MISSING: {f}')
    if absent:
        cmd = (
            'python scripts/embed_layers_h5.py \\\n'
            f'    --fasta {train_fasta} \\\n'
            f'            {val_fasta} \\\n'
            f'            {test_fasta} \\\n'
            f'    --layers {" ".join(str(l) for l in absent)}'
        )
        print(f'\nGenerate missing embeddings with:\n  {cmd}\n')
    for fasta in (train_fasta, val_fasta, test_fasta):
        remap = remapped(fasta)
        if not remap.exists():
            sys.exit(f'ERROR: remapped FASTA not found: {remap}')
    return ready


# ──────────────────────────────────────────────────────────────────────────────
# Config generation
# ──────────────────────────────────────────────────────────────────────────────

def make_config(
    base_path: Path, dst_path: Path,
    train_fasta: Path, val_fasta: Path, test_fasta: Path,
    layer: int, seed: int, experiment_name: str,
) -> None:
    with open(base_path) as f:
        cfg = yaml.safe_load(f)

    cfg['seed']              = seed
    cfg['experiment_name']   = experiment_name
    cfg['train_embeddings']  = str(layer_h5(train_fasta, layer))
    cfg['val_embeddings']    = str(layer_h5(val_fasta,   layer))
    cfg['test_embeddings']   = str(layer_h5(test_fasta,  layer))
    cfg['train_remapping']   = str(remapped(train_fasta))
    cfg['val_remapping']     = str(remapped(val_fasta))
    cfg['test_remapping']    = str(remapped(test_fasta))
    cfg['key_format']        = 'hash'

    dst_path.parent.mkdir(parents=True, exist_ok=True)
    with open(dst_path, 'w') as f:
        yaml.safe_dump(cfg, f, sort_keys=False)


# ──────────────────────────────────────────────────────────────────────────────
# Subprocess runner
# ──────────────────────────────────────────────────────────────────────────────

def run_one(config_path: Path, log_path: Path, train_script: str) -> int:
    cmd = [sys.executable, '-u', train_script, '--config', str(config_path)]
    print(f'  → {" ".join(cmd)}')
    print(f'    log: {log_path}')
    env = os.environ.copy()
    env['PYTHONUNBUFFERED'] = '1'
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, 'w') as logf:
        proc = subprocess.Popen(
            cmd, cwd=PROJECT_ROOT, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, env=env, text=True, bufsize=1,
        )
        for line in proc.stdout:
            logf.write(line)
            logf.flush()
        proc.wait()
    return proc.returncode


# ──────────────────────────────────────────────────────────────────────────────
# Result parsing
# ──────────────────────────────────────────────────────────────────────────────

def find_run_dir(experiment_name: str) -> Path | None:
    runs_root = PROJECT_ROOT / 'runs'
    if not runs_root.exists():
        return None
    candidates = [d for d in runs_root.iterdir()
                  if d.is_dir() and f'_{experiment_name}_' in d.name]
    return max(candidates, key=lambda d: d.stat().st_mtime) if candidates else None


def parse_eval(path: Path, task: str) -> dict:
    out = {}
    if task == 'meltome':
        pattern = r'^(Spearman R|Spearman stderr|MSE|MAE): ([\-0-9.eE+]+)'
    else:
        pattern = r'^(Accuracy|Accuracy stderr|MCC|MCC stderr|F1|F1 stderr): ([\-0-9.]+)'
    with open(path) as f:
        for line in f:
            m = re.match(pattern, line)
            if m:
                key = m.group(1).lower().replace(' ', '_')
                out[key] = float(m.group(2))
    return out


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description='Layer sweep: head-to-head pooling comparison at each ProtX layer.'
    )
    p.add_argument('--train-fasta', type=Path, required=True)
    p.add_argument('--val-fasta',   type=Path, required=True)
    p.add_argument('--test-fasta',  type=Path, required=True)
    p.add_argument('--task',    default='meltome', choices=['loc', 'meltome'])
    p.add_argument('--methods', nargs='+', default=DEFAULT_METHODS,
                   choices=['mean', 'cov', 'hybrid', 'la', 'la_cov'])
    p.add_argument('--layers',  nargs='+', type=int, default=DEFAULT_LAYERS,
                   help='ProtX layers to evaluate. Default: early/middle/late/last = 6 12 18 24.')
    p.add_argument('--seed',    type=int, default=123)
    p.add_argument('--tag',     default=None, help='Sweep folder name (default: timestamped).')
    return p.parse_args()


def main() -> None:
    args = parse_args()
    train_script   = TRAIN_SCRIPTS[args.task]
    task_base_cfgs = BASE_CONFIGS[args.task]

    tag       = args.tag or datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    sweep_dir = PROJECT_ROOT / 'sweeps' / f'layer_{tag}'
    print(f'Sweep dir: {sweep_dir}')
    print(f'Task: {args.task}   Train script: {train_script}')
    print(f'Layers:  {args.layers}')
    print(f'Methods: {args.methods}')

    # ── Validate ──────────────────────────────────────────────────────────────
    ready_layers = validate_inputs(
        args.train_fasta, args.val_fasta, args.test_fasta, args.layers,
    )
    if not ready_layers:
        sys.exit('No layers have H5 files ready — run embed_layers_h5.py first.')

    # ── Run grid: (layer, method) ──────────────────────────────────────────────
    plan = [(layer, method) for layer in ready_layers for method in args.methods]
    print(f'\n{len(plan)} runs total ({len(ready_layers)} layers × {len(args.methods)} methods)\n')

    all_rows: list[dict] = []

    for i, (layer, method) in enumerate(plan, 1):
        exp_name    = f'layer{layer:02d}_{method}_{args.task}_seed{args.seed}'
        config_path = sweep_dir / 'configs' / f'layer{layer:02d}_{method}.yaml'
        log_path    = sweep_dir / 'logs'    / f'layer{layer:02d}_{method}.log'

        make_config(
            task_base_cfgs[method], config_path,
            args.train_fasta, args.val_fasta, args.test_fasta,
            layer, args.seed, exp_name,
        )

        print(f'[{i:2d}/{len(plan)}] layer={layer:2d}  method={method}')
        t0 = datetime.datetime.now()
        rc = run_one(config_path, log_path, train_script)
        elapsed = (datetime.datetime.now() - t0).total_seconds() / 60.0
        print(f'       {"ok" if rc == 0 else f"FAILED rc={rc}"}  ({elapsed:.1f} min)')

        metrics: dict = {}
        run_dir = find_run_dir(exp_name)
        if run_dir:
            eval_file = run_dir / 'evaluation_test_set_after_train.txt'
            if eval_file.exists():
                metrics = parse_eval(eval_file, args.task)

        all_rows.append({'layer': layer, 'method': method, 'rc': rc,
                         'elapsed_min': round(elapsed, 1), **metrics})

    # ── Summary table ─────────────────────────────────────────────────────────
    print('\n' + '=' * 70)
    print('Layer × method sweep complete.\n')

    if args.task == 'meltome':
        print(f'{"Layer":>6}  {"Method":8}  {"SpearmanR":>10}  {"±stderr":>8}  {"MSE":>12}')
        for r in all_rows:
            rho = r.get('spearman_r', float('nan'))
            se  = r.get('spearman_stderr', float('nan'))
            mse = r.get('mse', float('nan'))
            print(f'{r["layer"]:>6}  {r["method"]:8}  {rho:>10.4f}  {se:>8.4f}  {mse:>12.7f}')
    else:
        print(f'{"Layer":>6}  {"Method":8}  {"Accuracy":>9}  {"MCC":>8}')
        for r in all_rows:
            acc = r.get('accuracy', float('nan'))
            mcc = r.get('mcc', float('nan'))
            print(f'{r["layer"]:>6}  {r["method"]:8}  {acc:>9.4f}  {mcc:>8.4f}')

    # ── CSV ───────────────────────────────────────────────────────────────────
    csv_path = sweep_dir / 'layer_results.csv'
    if all_rows:
        sweep_dir.mkdir(parents=True, exist_ok=True)
        with open(csv_path, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=list(all_rows[0].keys()))
            writer.writeheader()
            writer.writerows(all_rows)
        print(f'\nResults → {csv_path}')
        print(f'Plot    → python scripts/plot_layer_sweep.py --csv {csv_path}')


if __name__ == '__main__':
    main()
