#!/usr/bin/env python3
"""
Layer sweep — repeat the head-to-head pooling comparison across ProtX layers.

From the project spec (Section 5.1):
  "Layer sweep: repeat the head-to-head on a handful of layers
   (last, last-4, middle, early) — does covariance pooling's advantage hold
   across layers?"

For every (layer, method) pair the script:
  1. Builds a temporary config with the embedding paths overridden to the
     per-layer H5 files generated by embed_layers_h5.py.
  2. Runs train_meltome.py / train.py as a subprocess.
  3. After all runs finish, prints a (layer × method) results table.

Default layers map to quartiles of ProtX depth (24 encoder blocks):
    6  → early    (~25 %)
   12  → middle   (~50 %)
   18  → late     (~75 %)
   24  → last     (100 %)

Prerequisites — generate the per-layer H5 files first (GPU-intensive, one-time):
    python scripts/embed_layers_h5.py \\
        --fasta <train.fasta> <val.fasta> <test.fasta> \\
        --layers 6 12 18 24

Usage (Meltome):
    python scripts/run_layer_sweep.py \\
        --train-fasta data_files/flip_meltome/prepared/human_cell/human_cell_train.fasta \\
        --val-fasta   data_files/flip_meltome/prepared/human_cell/human_cell_val.fasta \\
        --test-fasta  data_files/flip_meltome/prepared/human_cell/human_cell_test.fasta \\
        --task meltome --methods mean cov hybrid --layers 6 12 18 24

Usage (DeepLoc):
    python scripts/run_layer_sweep.py \\
        --train-fasta data_files/deeploc_our_train_set.fasta \\
        --val-fasta   data_files/deeploc_our_val_set.fasta \\
        --test-fasta  data_files/deeploc_test_set.fasta \\
        --task loc --methods mean cov hybrid
"""

from __future__ import annotations

import argparse
import csv
import datetime
import os
import re
import subprocess
import sys
from pathlib import Path

import yaml


PROJECT_ROOT = Path(__file__).resolve().parent.parent

TRAIN_SCRIPTS = {
    'loc':     'train_subcellular_localization.py',
    'meltome': 'train_meltome.py',
}

# Base configs used to inherit all hyperparameters (lr, batch, patience, …).
# Embedding paths are overridden per (layer, method) run.
BASE_CONFIGS = {
    'loc': {
        'mean':   PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'mean.yaml',
        'cov':    PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'cov.yaml',
        'hybrid': PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'hybrid.yaml',
        'la':     PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'la.yaml',
        'la_cov': PROJECT_ROOT / 'configs' / 'subcellular_localization' / 'la_cov.yaml',
    },
    'meltome': {
        'mean':   PROJECT_ROOT / 'configs' / 'meltome' / 'mean.yaml',
        'cov':    PROJECT_ROOT / 'configs' / 'meltome' / 'cov.yaml',
        'hybrid': PROJECT_ROOT / 'configs' / 'meltome' / 'hybrid.yaml',
        'la':     PROJECT_ROOT / 'configs' / 'meltome' / 'la.yaml',
        'la_cov': PROJECT_ROOT / 'configs' / 'meltome' / 'la_cov.yaml',
    },
}

DEFAULT_LAYERS  = [6, 12, 18, 24]
DEFAULT_METHODS = ['mean', 'cov', 'hybrid', 'la', 'la_cov']


# ──────────────────────────────────────────────────────────────────────────────
# Path helpers  (mirror the naming from embed_layers_h5.py)
# ──────────────────────────────────────────────────────────────────────────────

# Single-layer dim for ProtT5-XL-U50 (one of the 24 transformer block outputs).
PROT_T5_DIM = 1024
# Layers concatenated to form the "stacked" embedding.
STACKED_LAYERS = [6, 12, 18, 24]
STACKED_DIM    = PROT_T5_DIM * len(STACKED_LAYERS)   # 4096


def layer_h5(fasta: Path, layer) -> Path:
    """Resolve the h5 file for a layer.  Integer layers use `_layerNN.h5`;
    the string 'stacked' uses `_layerStacked.h5`."""
    if isinstance(layer, str) and layer.lower() == 'stacked':
        return fasta.with_name(f"{fasta.stem}_layerStacked.h5")
    return fasta.with_name(f"{fasta.stem}_layer{int(layer):02d}.h5")


def layer_tag(layer) -> str:
    if isinstance(layer, str) and layer.lower() == 'stacked':
        return 'Stacked'
    return f'{int(layer):02d}'


def parse_layer(s: str):
    """argparse type for --layers: accepts integers or the keyword 'stacked'."""
    if s.lower() == 'stacked':
        return 'stacked'
    return int(s)


def remapped(fasta: Path) -> Path:
    return fasta.with_name(f"{fasta.stem}_remapped.fasta")


# ──────────────────────────────────────────────────────────────────────────────
# Validation
# ──────────────────────────────────────────────────────────────────────────────

def validate_inputs(
    train_fasta: Path, val_fasta: Path, test_fasta: Path, layers: list[int],
) -> list[int]:
    """Return the subset of layers for which all three H5 files already exist."""
    ready, absent = [], []
    for layer in layers:
        files = [layer_h5(f, layer) for f in (train_fasta, val_fasta, test_fasta)]
        if all(f.exists() for f in files):
            ready.append(layer)
        else:
            absent.append(layer)
            for f in files:
                if not f.exists():
                    print(f'  MISSING: {f}')
    if absent:
        cmd = (
            'python scripts/embed_layers_h5.py \\\n'
            f'    --fasta {train_fasta} \\\n'
            f'            {val_fasta} \\\n'
            f'            {test_fasta} \\\n'
            f'    --layers {" ".join(str(l) for l in absent)}'
        )
        print(f'\nGenerate missing embeddings with:\n  {cmd}\n')
    for fasta in (train_fasta, val_fasta, test_fasta):
        remap = remapped(fasta)
        if not remap.exists():
            sys.exit(f'ERROR: remapped FASTA not found: {remap}')
    return ready


# ──────────────────────────────────────────────────────────────────────────────
# Config generation
# ──────────────────────────────────────────────────────────────────────────────

def make_config(
    base_path: Path, dst_path: Path,
    train_fasta: Path, val_fasta: Path, test_fasta: Path,
    layer, seed: int, experiment_name: str,
    dc: int | None = None,
) -> None:
    with open(base_path) as f:
        cfg = yaml.safe_load(f)

    cfg['seed']              = seed
    cfg['experiment_name']   = experiment_name
    cfg['train_embeddings']  = str(layer_h5(train_fasta, layer))
    cfg['val_embeddings']    = str(layer_h5(val_fasta,   layer))
    cfg['test_embeddings']   = str(layer_h5(test_fasta,  layer))
    cfg['train_remapping']   = str(remapped(train_fasta))
    cfg['val_remapping']     = str(remapped(val_fasta))
    cfg['test_remapping']    = str(remapped(test_fasta))
    cfg['key_format']        = 'hash'

    # Override proj_dim if a --dc was passed and the method has proj_dim.
    mp = cfg.setdefault('model_parameters', {})
    if dc is not None and 'proj_dim' in mp:
        mp['proj_dim'] = dc

    # Stacked layer: embeddings are 4096-dim (4 × 1024). The trainer detects
    # this automatically from train_set[0][0].shape[-1] and passes it as
    # `embeddings_dim` to the model constructor — we must NOT also set it in
    # model_parameters or we'd get "multiple values for keyword argument".
    if isinstance(layer, str) and layer.lower() == 'stacked':
        # MPS has a 2^31 element limit on tensors. With 4096-dim embeddings
        # and max_length=6000, batch must stay <= 87. Cap at 64 for headroom.
        STACKED_BATCH_CAP = 64
        cur = cfg.get('batch_size', STACKED_BATCH_CAP)
        if cur > STACKED_BATCH_CAP:
            cfg['batch_size'] = STACKED_BATCH_CAP

    dst_path.parent.mkdir(parents=True, exist_ok=True)
    with open(dst_path, 'w') as f:
        yaml.safe_dump(cfg, f, sort_keys=False)


# ──────────────────────────────────────────────────────────────────────────────
# Subprocess runner
# ──────────────────────────────────────────────────────────────────────────────

def run_one(config_path: Path, log_path: Path, train_script: str) -> int:
    cmd = [sys.executable, '-u', train_script, '--config', str(config_path)]
    print(f'  → {" ".join(cmd)}')
    print(f'    log: {log_path}')
    env = os.environ.copy()
    env['PYTHONUNBUFFERED'] = '1'
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, 'w') as logf:
        proc = subprocess.Popen(
            cmd, cwd=PROJECT_ROOT, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, env=env, text=True, bufsize=1,
        )
        for line in proc.stdout:
            logf.write(line)
            logf.flush()
        proc.wait()
    return proc.returncode


# ──────────────────────────────────────────────────────────────────────────────
# Result parsing
# ──────────────────────────────────────────────────────────────────────────────

def find_run_dir(experiment_name: str) -> Path | None:
    runs_root = PROJECT_ROOT / 'runs'
    if not runs_root.exists():
        return None
    candidates = [d for d in runs_root.iterdir()
                  if d.is_dir() and f'_{experiment_name}_' in d.name]
    return max(candidates, key=lambda d: d.stat().st_mtime) if candidates else None


def parse_eval(path: Path, task: str) -> dict:
    out = {}
    if task == 'meltome':
        pattern = r'^(Spearman R|Spearman stderr|MSE|MAE): ([\-0-9.eE+]+)'
    else:
        pattern = r'^(Accuracy|Accuracy stderr|MCC|MCC stderr|F1|F1 stderr): ([\-0-9.]+)'
    with open(path) as f:
        for line in f:
            m = re.match(pattern, line)
            if m:
                key = m.group(1).lower().replace(' ', '_')
                out[key] = float(m.group(2))
    return out


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description='Layer sweep: head-to-head pooling comparison at each ProtX layer.'
    )
    p.add_argument('--tasks',   nargs='+', default=['meltome'],
                   choices=['loc', 'meltome'],
                   help='One or more tasks. Each task auto-resolves its FASTA paths '
                        'unless --train-fasta / --val-fasta / --test-fasta are given '
                        '(in which case they apply to all listed tasks).')
    p.add_argument('--train-fasta', type=Path, default=None)
    p.add_argument('--val-fasta',   type=Path, default=None)
    p.add_argument('--test-fasta',  type=Path, default=None)
    p.add_argument('--methods', nargs='+', default=DEFAULT_METHODS,
                   choices=['mean', 'cov', 'hybrid', 'la', 'la_cov'])
    p.add_argument('--layers',  nargs='+', type=parse_layer, default=DEFAULT_LAYERS,
                   help='ProtX layers to evaluate. Default: early/middle/late/last = 6 12 18 24. '
                        'Pass the keyword "stacked" to also include the concatenated '
                        '6+12+18+24 (4096-dim) variant — requires `_layerStacked.h5` to exist '
                        '(use scripts/stack_layers.py to generate it).')
    p.add_argument('--seeds',   nargs='+', type=int, default=[123],
                   help='One or more random seeds, e.g. --seeds 657 921 969.')
    p.add_argument('--dc',      type=int, default=None,
                   help='Override proj_dim (d_c) for cov/hybrid/la_cov methods. '
                        'Falls back to the base config value if omitted.')
    p.add_argument('--tag',     default=None, help='Sweep folder name (default: timestamped).')
    return p.parse_args()


# ──────────────────────────────────────────────────────────────────────────────
# Per-task default FASTA paths
# ──────────────────────────────────────────────────────────────────────────────

DEFAULT_TASK_FASTAS = {
    'loc': {
        'train': PROJECT_ROOT / 'data_files' / 'deeploc_our_train_set.fasta',
        'val':   PROJECT_ROOT / 'data_files' / 'deeploc_our_val_set.fasta',
        'test':  PROJECT_ROOT / 'data_files' / 'deeploc_test_set.fasta',
    },
    'meltome': {
        'train': PROJECT_ROOT / 'data_files' / 'flip_meltome' / 'prepared' / 'human_cell' / 'human_cell_train.fasta',
        'val':   PROJECT_ROOT / 'data_files' / 'flip_meltome' / 'prepared' / 'human_cell' / 'human_cell_val.fasta',
        'test':  PROJECT_ROOT / 'data_files' / 'flip_meltome' / 'prepared' / 'human_cell' / 'human_cell_test.fasta',
    },
}


def _resolve_fastas(task: str, args) -> tuple[Path, Path, Path]:
    """Pick FASTA paths: explicit CLI overrides first, else per-task defaults."""
    defaults = DEFAULT_TASK_FASTAS[task]
    train = args.train_fasta or defaults['train']
    val   = args.val_fasta   or defaults['val']
    test  = args.test_fasta  or defaults['test']
    return train, val, test


def run_task(task: str, args, sweep_dir: Path) -> list[dict]:
    train_script   = TRAIN_SCRIPTS[task]
    task_base_cfgs = BASE_CONFIGS[task]
    train_fasta, val_fasta, test_fasta = _resolve_fastas(task, args)

    print(f'\n{"=" * 70}')
    print(f'Task: {task}   Train script: {train_script}')
    print(f'  train: {train_fasta}')
    print(f'  val:   {val_fasta}')
    print(f'  test:  {test_fasta}')

    ready_layers = validate_inputs(train_fasta, val_fasta, test_fasta, args.layers)
    if not ready_layers:
        print(f'No layers have H5 files ready for {task}; skipping this task.')
        return []

    plan = [(seed, layer, method)
             for seed in args.seeds
             for layer in ready_layers
             for method in args.methods]
    print(f'{len(plan)} runs for task={task} '
          f'({len(args.seeds)} seeds × {len(ready_layers)} layers × {len(args.methods)} methods)\n')

    all_rows: list[dict] = []
    for i, (seed, layer, method) in enumerate(plan, 1):
        dc_tag      = f'_dc{args.dc}' if args.dc is not None else ''
        ltag        = layer_tag(layer)
        exp_name    = f'layer{ltag}_{method}{dc_tag}_{task}_seed{seed}'
        config_path = sweep_dir / 'configs' / f'{task}_layer{ltag}_{method}{dc_tag}_seed{seed}.yaml'
        log_path    = sweep_dir / 'logs'    / f'{task}_layer{ltag}_{method}{dc_tag}_seed{seed}.log'

        make_config(
            task_base_cfgs[method], config_path,
            train_fasta, val_fasta, test_fasta,
            layer, seed, exp_name, dc=args.dc,
        )

        print(f'[{i:2d}/{len(plan)}] task={task}  seed={seed}  '
              f'layer={ltag:>8}  method={method}')
        t0 = datetime.datetime.now()
        rc = run_one(config_path, log_path, train_script)
        elapsed = (datetime.datetime.now() - t0).total_seconds() / 60.0
        print(f'       {"ok" if rc == 0 else f"FAILED rc={rc}"}  ({elapsed:.1f} min)')

        metrics: dict = {}
        run_dir = find_run_dir(exp_name)
        if run_dir:
            eval_file = run_dir / 'evaluation_test_set_after_train.txt'
            if eval_file.exists():
                metrics = parse_eval(eval_file, task)

        all_rows.append({'task': task, 'layer': layer, 'method': method,
                         'seed': seed, 'rc': rc,
                         'elapsed_min': round(elapsed, 1), **metrics})
    return all_rows


def main() -> None:
    args = parse_args()

    tag       = args.tag or datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
    sweep_dir = PROJECT_ROOT / 'sweeps' / f'layer_{tag}'
    print(f'Sweep dir: {sweep_dir}')
    print(f'Tasks:   {args.tasks}')
    print(f'Layers:  {args.layers}')
    print(f'Methods: {args.methods}')
    print(f'd_c:     {args.dc if args.dc is not None else "from base configs"}')
    print(f'Seeds:   {args.seeds}')

    all_rows: list[dict] = []
    for task in args.tasks:
        all_rows.extend(run_task(task, args, sweep_dir))

    # ── Per-task summary tables ───────────────────────────────────────────────
    print('\n' + '=' * 70)
    print('Layer × method sweep complete.')

    for task in args.tasks:
        task_rows = [r for r in all_rows if r.get('task') == task]
        if not task_rows:
            continue
        print(f'\n--- Task: {task} ---')
        if task == 'meltome':
            print(f'{"Layer":>8}  {"Method":8}  {"Seed":>5}  '
                  f'{"SpearmanR":>10}  {"±stderr":>8}  {"MSE":>12}')
            for r in task_rows:
                rho = r.get('spearman_r', float('nan'))
                se  = r.get('spearman_stderr', float('nan'))
                mse = r.get('mse', float('nan'))
                print(f'{str(r["layer"]):>8}  {r["method"]:8}  {r.get("seed", ""):>5}  '
                      f'{rho:>10.4f}  {se:>8.4f}  {mse:>12.7f}')
        else:
            print(f'{"Layer":>8}  {"Method":8}  {"Seed":>5}  {"Accuracy":>9}  {"MCC":>8}')
            for r in task_rows:
                acc = r.get('accuracy', float('nan'))
                mcc = r.get('mcc', float('nan'))
                print(f'{str(r["layer"]):>8}  {r["method"]:8}  {r.get("seed", ""):>5}  '
                      f'{acc:>9.4f}  {mcc:>8.4f}')

    # ── CSV (one combined file with a task column) ────────────────────────────
    csv_path = sweep_dir / 'layer_results.csv'
    if all_rows:
        sweep_dir.mkdir(parents=True, exist_ok=True)
        fields = sorted({k for r in all_rows for k in r.keys()})
        with open(csv_path, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            for r in all_rows:
                writer.writerow({k: r.get(k, '') for k in fields})
        print(f'\nResults → {csv_path}')
        print(f'Plot    → python scripts/plot_layer_sweep.py --csv {csv_path}')


if __name__ == '__main__':
    main()
